/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smanempat.view;

import com.smanempat.controller.ControllerTesting;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zakaria
 */
public class ComboBoxWithCheckBox extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    DefaultTableModel tableModelTampil;
    static Connection conn = null;
    Object[][] dataUser = null;
//    String[] kolomUser = new String[]{
//        "Tahun", "Selected"};

    /**
     * Creates new form ComboBoxWithCheckBox
     */
    // ControllerTesting conTest = new ControllerTesting();
    public ComboBoxWithCheckBox() {
        initComponents();
        tableModel = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(tableModel);
        tableModelTampil = (DefaultTableModel) jTable2.getModel();
        jTable2.setModel(tableModelTampil);
        //this.mini

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tahun", "Selected"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tahun", "NIS", "Nama"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ControllerTesting conTest = new ControllerTesting();
        conTest.showTahunAjaran(jTable1);

//        try {
//            //hapusTabel();
////            int row = tableModel.getRowCount();
////        for (int i = 0; i < row; i++) {
////            tableModel.removeRow(0);
////        }
//            connect();
//            Statement state = conn.createStatement();
//            String query = "SELECT * FROM Tahun";
//            ResultSet rs = state.executeQuery(query);
//            while (rs.next()) {
//                String tahun = rs.getString("Tahun");
////                Boolean cb = false;
//
//                String isiTabel = (tahun);
//
//                tableModel.addRow(new Object[]{
//                    isiTabel, false
//                });
//            }
//            jTable1.setModel(tableModel);
//            rs.close();
//            conn.close();
//        } catch (SQLException error) {
//            System.out.println(error);
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //hapusTabel();
        int row = tableModelTampil.getRowCount();
        for (int i = 0; i < row; i++) {
            tableModelTampil.removeRow(0);
        }
        int rc = jTable1.getRowCount();
        String tempArray[] = new String[rc];
        String hasil = "";
        System.out.println("rcnya segini " + rc);
        for (int i = 0; i < rc; i++) {
            boolean bool = Boolean.valueOf("" + jTable1.getValueAt(i, 1));
            System.out.println(bool);
            if (bool) {

                tempArray[i] = (String) jTable1.getValueAt(i, 0);
                System.out.println(tempArray[i]);
                tampilTabel(tempArray[i]);
                hasil += "*" + jTable1.getValueAt(i, 0);
            }

        }
        JOptionPane.showMessageDialog(null, hasil);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        connect();

        //conTest.showTahunAjaran(jTable1);
        // tampil();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBoxWithCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBoxWithCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBoxWithCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBoxWithCheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBoxWithCheckBox().setVisible(true);
            }
        });
    }

    private static void connect() {
        // SQLite connection string
        String url = "jdbc:sqlite:D:\\NetBeansProjects\\SMA Negeri 4 Tangerang Selatan\\db\\Mahasiswa.db";

        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        //return conn;
    }

    public void tampil() {
        jTable1.setModel(tableModel);
        tableModel.removeRow(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void tampilTabel(String par) {
        try {
            //hapusTabel();
//            int row = tableModel.getRowCount();
//        for (int i = 0; i < row; i++) {
//            tableModel.removeRow(0);
//        }
            connect();
            Statement state = conn.createStatement();

            String query = "SELECT * FROM Siswa WHERE Tahun = '" + par + "'";
            ResultSet rs = state.executeQuery(query);
            while (rs.next()) {
                String nis = rs.getString("NIS");
                String nama = rs.getString("Nama");
//                Boolean cb = false;

                String isiTabel[] = {nis, nama};

                tableModelTampil.addRow(isiTabel);
            }
            jTable2.setModel(tableModelTampil);
            rs.close();
            conn.close();
        } catch (SQLException error) {
            System.out.println(error);
        }
    }
}
